# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Artem Sychov
email: artem.suchov@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   All content here is in <a href='https://creativecommons.org/publicdomain/zero/1.0/'>public domain</a>. An attribution would be nice though.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://suchov.com" # the base hostname & protocol for your site
twitter_username: ArtemSuchov
github_username:  suchov

# Build settings
markdown: kramdown
